version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: create result dir
          command: |
            mkdir -p ~/tmp/test-results
          when: always
      - run: npm run browser-list
      # - run: npm test
      - run: npm run ci-test
      - store_artifacts:
          path: /tmp/test-results
          prefix: tests
      - store_test_results:
          path: /tmp/test-results
          prefix: tests
